version: '3'

services:
  sampleproject:
    image: drill4j/real-world-angular:java-and-js-coverage-${REALWORLD_BUILD_VERSION}
    environment:
      DRILL_JS_AGENT_HOST: ${DRILL_JS_AGENT_HOST}
      DRILL_JS_AST_PARSER_VERSION: ${DRILL_JS_AST_PARSER_VERSION}
      DRILL_JS_AGENT_AGENT_ID: ${DRILL_JS_AGENT_AGENT_ID}
      DRILL_JS_AGENT_GROUP_ID: ${DRILL_JS_AGENT_GROUP_ID}
      REALWORLD_BUILD_VERSION: ${REALWORLD_BUILD_VERSION}
      REALWORLD_API_ADDRESS: ${REALWORLD_API_ADDRESS}
    ports:
      - "${REALWORLD_PORT}:80"
